//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieFlix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovieList()
        {
            this.payments = new HashSet<payment>();
        }
    
        public int movieID { get; set; }
        public string movieName { get; set; }
        public Nullable<System.DateTime> reliseDate { get; set; }
        public Nullable<int> rating { get; set; }
        public string trailerLink { get; set; }
        public string moviePoster { get; set; }
        public string movieLink { get; set; }
        public string moivePrice { get; set; }
        public string detailesPoster { get; set; }
        public string movieDetailes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment> payments { get; set; }
    }
}
